include:
  - apache2
  - lencrypt
  - mysql.database
  - mysql.user
  - mysql_cc.root_my_cnf
  - nodejs
  - php.ng.apache2
  - php.ng.cli
  - php.ng.gd
  - php.ng.mysqlnd
  - php.ng.xml
  - php_cc.composer
  - wordpress.cli
