#!/bin/bash
set -o errexit
set -o errtrace
set -o nounset

# shellcheck disable=SC2154
trap '_es=${?};
    printf "${0}: line ${LINENO}: \"${BASH_COMMAND}\"";
    printf " exited with a status of ${_es}\n";
    exit ${_es}' ERR

# shellcheck disable=SC1091


echo 'Install WordPress' 
# Call WP-CLI with appropriate site arguments
#/usr/local/bin/wp --path="${WP_DIR} "${@}" 
