#!/bin/bash
set -o errexit
set -o errtrace
set -o nounset

# shellcheck disable=SC2154
trap '_es=${?};
    printf "${0}: line ${LINENO}: \"${BASH_COMMAND}\"";
    printf " exited with a status of ${_es}\n";
    exit ${_es}' ERR

# shellcheck disable=SC1091
WEB_WP_DIR=${1}


echo 'Install WordPress at'  $WEB_WP_DIR
# Call WP-CLI with appropriate site arguments
/usr/local/bin/wp --path="${WEB_WP_DIR}"\
  "${@}" 
